from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1103, 869)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.find_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.find_pushButton.setGeometry(QtCore.QRect(490, 150, 111, 41))
        self.find_pushButton.setObjectName("find_pushButton")
        self.renew_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.renew_pushButton.setGeometry(QtCore.QRect(490, 220, 111, 41))
        self.renew_pushButton.setObjectName("renew_pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(490, 290, 111, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.add_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.add_pushButton.setGeometry(QtCore.QRect(490, 80, 211, 41))
        self.add_pushButton.setObjectName("add_pushButton")
        self.id_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.id_lineEdit.setGeometry(QtCore.QRect(290, 80, 181, 41))
        self.id_lineEdit.setObjectName("id_lineEdit")
        self.lname_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lname_lineEdit.setGeometry(QtCore.QRect(290, 150, 181, 41))
        self.lname_lineEdit.setObjectName("lname_lineEdit")
        self.fname_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.fname_lineEdit.setGeometry(QtCore.QRect(290, 220, 181, 41))
        self.fname_lineEdit.setObjectName("fname_lineEdit")
        self.subject_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.subject_lineEdit.setGeometry(QtCore.QRect(290, 290, 181, 41))
        self.subject_lineEdit.setObjectName("subject_lineEdit")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(290, 430, 181, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.id_label = QtWidgets.QLabel(self.centralwidget)
        self.id_label.setGeometry(QtCore.QRect(90, 80, 121, 41))
        self.id_label.setObjectName("id_label")
        self.lname_label = QtWidgets.QLabel(self.centralwidget)
        self.lname_label.setGeometry(QtCore.QRect(90, 150, 121, 41))
        self.lname_label.setObjectName("lname_label")
        self.fname_label = QtWidgets.QLabel(self.centralwidget)
        self.fname_label.setGeometry(QtCore.QRect(90, 220, 121, 41))
        self.fname_label.setObjectName("fname_label")
        self.subject_label = QtWidgets.QLabel(self.centralwidget)
        self.subject_label.setGeometry(QtCore.QRect(90, 290, 121, 41))
        self.subject_label.setObjectName("subject_label")
        self.close_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.close_pushButton.setGeometry(QtCore.QRect(970, 770, 93, 28))
        self.close_pushButton.setObjectName("close_pushButton")
        self.score_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.score_lineEdit.setGeometry(QtCore.QRect(290, 360, 181, 41))
        self.score_lineEdit.setObjectName("score_lineEdit")
        self.score_label = QtWidgets.QLabel(self.centralwidget)
        self.score_label.setGeometry(QtCore.QRect(90, 360, 121, 41))
        self.score_label.setObjectName("score_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1103, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.find_pushButton.setText(_translate("MainWindow", "ძებნა"))
        self.renew_pushButton.setText(_translate("MainWindow", "განახლება"))
        self.pushButton_3.setText(_translate("MainWindow", "წაშლა"))
        self.add_pushButton.setText(_translate("MainWindow", "ყველა ჩანაწერის გაკეთება"))
        self.pushButton_5.setText(_translate("MainWindow", "ჩაწერა"))
        self.id_label.setText(_translate("MainWindow", "იდენტ."))
        self.lname_label.setText(_translate("MainWindow", "გვარი"))
        self.fname_label.setText(_translate("MainWindow", "სახელი"))
        self.subject_label.setText(_translate("MainWindow", "საგანი"))
        self.close_pushButton.setText(_translate("MainWindow", "Close"))
        self.score_label.setText(_translate("MainWindow", "შეფასება"))
